=== matteoventali/repository_homework/tesina/xml/schemaRisposte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="risposte">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="risposta" minOccurs="0" maxOccurs="unbounded" />  
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="risposta">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="contenuto" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="valutazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>

            <xsd:attribute name="id_domanda" type="xsd:integer" use="required" />
            <xsd:attribute name="id_utente" type="xsd:integer" use="required" />
            <xsd:attribute name="faq" type="xsd:boolean" use="required" />
            <xsd:attribute name="data" type="xsd:date" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="contenuto" type="xsd:string"/>

    <xsd:element name="valutazione">
        <xsd:complexType>
            <xsd:attribute name="rating" type="tipoRating" use="required" />
            <xsd:attribute name="id_utente" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoRating">
            <xsd:restriction base="xsd:integer">
                <xsd:minInclusive value="1" />
                <xsd:maxInclusive value="5" />
            </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== matteoventali/repository_homework/tesina/xml/risposte.xml
<?xml version="1.0" encoding="UTF-8"?>
<risposte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./schemaRisposte.xsd">

    <risposta id_domanda="1" id_utente="1" faq="false" data="2024-06-07">
        <contenuto>
            L'azienda non ha una sede fisica: opera esclusivamente online.
        </contenuto>
    </risposta>

    <risposta id_domanda="2" id_utente="14" faq="true" data="2024-06-07">
        <contenuto>
            Puoi inserire un indirizzo di consegna diverso prima di ultimare l'acquisto.
        </contenuto>
        <valutazione id_utente="1" rating="5"/>
        <valutazione id_utente="2" rating="5"/>
        <valutazione id_utente="17" rating="5"/>
    </risposta>
</risposte>

=== matteoventali/repository_homework/tesina/docs/latex/xmlCopia/risposte.xml
<?xml version="1.0" encoding="UTF-8"?>
<risposte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schemaRisposte.xsd">

    <risposta id="1" id_domanda="1" id_utente="1" faq="false" data="2024-06-07">
        <contenuto>
            L'azienda non ha una sede fisica: opera esclusivamente online.
        </contenuto>
        <valutazioni></valutazioni>
    </risposta>

    <risposta id="2" id_domanda="2" id_utente="14" faq="true" data="2024-06-07">
        <contenuto>
            Puoi inserire un indirizzo di consegna diverso prima di ultimare l'acquisto.
        </contenuto>
        <valutazioni>
            <valutazione peso="200" id_utente="1" rating="5"/>
            <valutazione peso="200" id_utente="2" rating="5"/>
            <valutazione peso="55"  id_utente="17" rating="5"/>
        </valutazioni>
    </risposta>
</risposte>
