=== matteoventali/repository_homework/tesina/xml/schemaDomande.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="domande">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="domanda" minOccurs="0" maxOccurs="unbounded" />  
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="domanda">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="contenuto" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="valutazioni" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>

            <xsd:attribute name="id" type="xsd:integer" use="required" />
            <xsd:attribute name="id_utente" type="xsd:integer" use="required" />
            <xsd:attribute name="faq" type="xsd:boolean" use="required" />
            <xsd:attribute name="data" type="xsd:date" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="contenuto" type="xsd:string"/>

    <xsd:element name="valutazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="valutazione" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="valutazione">
        <xsd:complexType>
            <xsd:attribute name="rating" type="tipoRating" use="required" />
            <xsd:attribute name="id_utente" type="xsd:integer" use="required" />
            <xsd:attribute name="peso" type="tipoPeso" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoRating">
            <xsd:restriction base="xsd:integer">
                <xsd:minInclusive value="1" />
                <xsd:maxInclusive value="5" />
            </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoPeso">
            <xsd:restriction base="xsd:integer">
                <xsd:minInclusive value="1" />
                <xsd:maxInclusive value="200" />
            </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== matteoventali/repository_homework/tesina/xml/domande.xml
<?xml version="1.0" encoding="UTF-8"?>
<domande xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./schemaDomande.xsd">

    <domanda id="1" id_utente="10" faq="false" data="2024-06-07">
        <contenuto>
            Avete una sede fisica?
        </contenuto>
        <valutazioni></valutazioni>
    </domanda>

    <domanda id="2" id_utente="11" faq="true" data="2024-06-06">
        <contenuto>
            Posso inserire un indirizzo di consegna diverso da quello presente nel profilo?
        </contenuto>
        <valutazioni>
            <valutazione peso="40" id_utente="10" rating="5"/>
            <valutazione peso="23" id_utente="12" rating="5"/>
            <valutazione peso="1" id_utente="13" rating="4"/>
        </valutazioni>
    </domanda>
</domande>

=== matteoventali/repository_homework/tesina/xml/documenti/domande.xml
<?xml version="1.0" encoding="UTF-8"?>
<domande xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaDomande.xsd"><domanda id="1" faq="true" data="2024-07-18" id_utente="2"><contenuto>Avete una sede fisica?</contenuto><valutazioni><valutazione id_utente="4" peso="13" rating="5"/></valutazioni></domanda><domanda id="2" faq="true" data="2024-07-18" id_utente="3"><contenuto>Si pu√≤ cambiare l'indirizzo di consegna?</contenuto><valutazioni><valutazione id_utente="1" peso="200" rating="1"/></valutazioni></domanda></domande>

=== matteoventali/repository_homework/tesina/docs/xml_pop/domande.xml
<?xml version="1.0" encoding="UTF-8"?>
<domande xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaDomande.xsd"><domanda id="1" faq="true" data="2024-07-26" id_utente="3"><contenuto>Avete una sede fisica?</contenuto><valutazioni><valutazione id_utente="4" peso="1" rating="3"/><valutazione id_utente="1" peso="200" rating="4"/></valutazioni></domanda><domanda id="2" faq="false" data="2024-07-26" id_utente="4"><contenuto>Si pu√≤ modificare l'indirizzo di consegna?</contenuto><valutazioni><valutazione id_utente="3" peso="1" rating="4"/></valutazioni></domanda><domanda id="3" faq="true" data="2024-07-26" id_utente="1"><contenuto>Quanto dura la garanzia sui prodotti?</contenuto><valutazioni/></domanda></domande>
