=== matteoventali/repository_homework/tesina/xml/schemaPortafogliBonus.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:element name="portafogli">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="portafoglio" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="portafoglio">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="saldo" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id_cliente" type="xsd:integer" use="required"></xsd:attribute>
            <xsd:attribute name="totale" type="xsd:integer" use="required"></xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="saldo">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:integer">
                  <xsd:attribute name="anno" type="xsd:integer"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== matteoventali/repository_homework/tesina/xml/documenti/portafogliBonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<portafogli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaPortafogliBonus.xsd"><portafoglio totale="0" id_cliente="3"><saldo anno="2024">0</saldo></portafoglio><portafoglio totale="0" id_cliente="4"><saldo anno="2021">20</saldo><saldo anno="2022">20</saldo><saldo anno="2023">5</saldo><saldo anno="2024">1</saldo></portafoglio><portafoglio totale="0" id_cliente="5"><saldo anno="2024">0</saldo></portafoglio><portafoglio totale="0" id_cliente="6"><saldo anno="2024">0</saldo></portafoglio><portafoglio totale="0" id_cliente="7"><saldo anno="2024">0</saldo></portafoglio></portafogli>

=== matteoventali/repository_homework/tesina/docs/xmlCopia/documenti/portafogliBonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<portafogli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schemaPortafogliBonus.xsd">
    <portafoglio id_cliente="10" totale="4">
        <saldo anno="2023">1</saldo>
        <saldo anno="2024">3</saldo>
    </portafoglio>

    <portafoglio id_cliente="50" totale="3">
        <saldo anno="2024">3</saldo>
    </portafoglio>

    <portafoglio id_cliente="23" totale="10">
        <saldo anno="2022">3</saldo>
        <saldo anno="2023">1</saldo>
        <saldo anno="2024">6</saldo>
    </portafoglio>
</portafogli>
