=== matteoventali/repository_homework/tesina/xml/schemaRecensioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="recensioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="recensione" minOccurs="0" maxOccurs="unbounded" />  
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="recensione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="contenuto" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="valutazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>

            <xsd:attribute name="id_cliente" type="xsd:integer" use="required" />
            <xsd:attribute name="id_prodotto" type="xsd:integer" use="required" />
            <xsd:attribute name="data" type="xsd:date" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="contenuto" type="xsd:string"/>

    <xsd:element name="valutazione">
        <xsd:complexType>
            <xsd:attribute name="rating" type="tipoRating" use="required" />
            <xsd:attribute name="id_utente" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoRating">
            <xsd:restriction base="xsd:integer">
                <xsd:minInclusive value="1" />
                <xsd:maxInclusive value="5" />
            </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== matteoventali/repository_homework/tesina/docs/documento_tesina/xmlCopia/documenti/recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<recensioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaRecensioni.xsd">

    <recensione id="1" id_cliente="10" id_prodotto="1" data="2024-06-07">
        <contenuto>
            Bellissimo computer, con ottime caratteristiche.
        </contenuto>
        <valutazioni></valutazioni>
    </recensione>

    <recensione id="2" id_cliente="11" id_prodotto="2" data="2024-06-06">
        <contenuto>
            Il televisore presenta un'ottima risoluzione e numerosi servizi.
        </contenuto>
        <valutazioni>
            <valutazione peso="23" id_utente="10" rating="5"/>
            <valutazione peso="48" id_utente="12" rating="4"/>
            <valutazione peso="92" id_utente="13" rating="2"/>
        </valutazioni>
    </recensione>
</recensioni>
