=== matteoventali/repository_homework/homework3/xml/partiteSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <!-- Elemento partite, radice del documento -->
    <xsd:element name="partite">
        <xsd:complexType> 
            <xsd:sequence>
                <xsd:element ref="partita" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Singola partita -->
    <xsd:element name="partita">
        <xsd:complexType>
            <xsd:sequence>
               <xsd:element type="xsd:string" name="squadraCasa" minOccurs="1" maxOccurs="1" />
               <xsd:element type="xsd:string" name="squadraOspite" minOccurs="1" maxOccurs="1" />
               <xsd:element type="xsd:unsignedInt" name="golCasa" minOccurs="1" maxOccurs="1" />
               <xsd:element type="xsd:unsignedInt" name="golOspite" minOccurs="1" maxOccurs="1" />
               <xsd:element type="xsd:string" name="data" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== matteoventali/repository_homework/homework3/xml/partite.xml
<?xml version="1.0"?>
<partite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml/partiteSchema.xsd"><partita><squadraCasa>Milan</squadraCasa><squadraOspite>Inter</squadraOspite><golCasa>1</golCasa><golOspite>1</golOspite><data>30/10/2023</data></partita><partita><squadraCasa>Juventus</squadraCasa><squadraOspite>Manchester United</squadraOspite><golCasa>0</golCasa><golOspite>10</golOspite><data>30/10/2023</data></partita><partita><squadraCasa>Inter</squadraCasa><squadraOspite>Real Madrid</squadraOspite><golCasa>1</golCasa><golOspite>4</golOspite><data>31/10/2021</data></partita><partita><squadraCasa>Juventus</squadraCasa><squadraOspite>Inter</squadraOspite><golCasa>1</golCasa><golOspite>3</golOspite><data>16/05/2024</data></partita></partite>
