=== matteoventali/repository_homework/tesina/docs/documento_tesina/xmlCopia/schema/schemaRichiesteRicariche.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="richieste">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="ricarica" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="ricarica">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="data_richiesta" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="crediti_richiesti" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="data_valutazione" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>

            <xsd:attribute name="id" type="xsd:integer" use="required"></xsd:attribute>
            <xsd:attribute name="id_cliente" type="xsd:integer" use="required"></xsd:attribute>
            <xsd:attribute name="id_admin" type="xsd:integer" use="optional"></xsd:attribute>
            <xsd:attribute name="stato" type="tipoStato" use="required"></xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="tipoStato">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="W"></xsd:enumeration>
            <xsd:enumeration value="R"></xsd:enumeration>
            <xsd:enumeration value="A"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="data_richiesta" type="xsd:string"/>
    <xsd:element name="data_valutazione" type="xsd:string"/>
    <xsd:element name="crediti_richiesti" type="xsd:string"/>

</xsd:schema>

=== matteoventali/repository_homework/tesina/docs/xml_pop/richiesteRicariche.xml
<?xml version="1.0" encoding="UTF-8"?>
<richieste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaRichiesteRicariche.xsd"><ricarica id="1" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>100</crediti_richiesti></ricarica><ricarica id="2" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>40</crediti_richiesti></ricarica><ricarica id="3" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>100</crediti_richiesti></ricarica><ricarica id="4" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>100</crediti_richiesti></ricarica><ricarica id="5" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>100</crediti_richiesti></ricarica><ricarica id="6" id_cliente="4" stato="A" id_admin="1"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>100</crediti_richiesti></ricarica><ricarica id="7" id_cliente="3" stato="W"><data_richiesta>2024-07-26</data_richiesta><crediti_richiesti>40</crediti_richiesti></ricarica></richieste>
