=== matteoventali/repository_homework/tesina/xml/schema/schemaAcquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="acquisti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="acquisto" minOccurs="0" maxOccurs="unbounded" />  
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="acquisto">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prodotti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="indirizzo_consegna" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>

            <xsd:attribute name="id" type="xsd:integer" use="required" />
            <xsd:attribute name="id_cliente" type="xsd:integer" use="required" />
            <xsd:attribute name="data" type="xsd:date" use="required" />
            <xsd:attribute name="crediti_bonus_ricevuti" type="xsd:integer" use="required" />
            <xsd:attribute name="crediti_bonus_utilizzati" type="xsd:integer" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prodotti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prodotto" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prodotto">
        <xsd:complexType>
            <xsd:attribute name="id_prodotto" type="xsd:integer" use="required" />
            <xsd:attribute name="prezzo" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="indirizzo_consegna" type="xsd:string" />

</xsd:schema>

=== matteoventali/repository_homework/tesina/docs/xml_pop/acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<acquisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaAcquisti.xsd"><acquisto id="1" id_cliente="4" data="2024-07-26" crediti_bonus_ricevuti="5" crediti_bonus_utilizzati="0" totale_effettivo="334"><prodotti><prodotto id_prodotto="1" prezzo="260"/><prodotto id_prodotto="3" prezzo="74"/></prodotti><indirizzo_consegna>Via Milano 1</indirizzo_consegna></acquisto><acquisto id="2" id_cliente="4" data="2024-07-26" crediti_bonus_ricevuti="7" crediti_bonus_utilizzati="0" totale_effettivo="153"><prodotti><prodotto id_prodotto="2" prezzo="153"/></prodotti><indirizzo_consegna>Via Milano 1</indirizzo_consegna></acquisto></acquisti>

=== matteoventali/repository_homework/tesina/docs/xmlCopia/documenti/acquisti.xml
<?xml version="1.0" encoding="UTF-8" ?>
<acquisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaAcquisti.xsd" >
       
    <acquisto id="1" id_cliente="10" data="2024-06-08" crediti_bonus_ricevuti="3">
        <prodotti>
            <prodotto id_prodotto="1" prezzo="170"/>
        </prodotti>
        <indirizzo_consegna>Via Rossi 15 Latina 04100</indirizzo_consegna>
    </acquisto>
    
    <acquisto id="2" id_cliente="50" data="2024-06-10" crediti_bonus_ricevuti="3">
        <prodotti>
            <prodotto id_prodotto="2" prezzo="67"/>
        </prodotti>
        <indirizzo_consegna>Via Verdi 1 Roma 00042</indirizzo_consegna>
    </acquisto>

    <acquisto id="3" id_cliente="23" data="2024-06-15" crediti_bonus_ricevuti="6">
        <prodotti>
            <prodotto id_prodotto="1" prezzo="170"/>
            <prodotto id_prodotto="2" prezzo="67"/>
        </prodotti>
        <indirizzo_consegna>Via Neri 78 Aosta 11100</indirizzo_consegna>
    </acquisto>
</acquisti>

=== matteoventali/repository_homework/tesina/xml/documenti/acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<acquisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaAcquisti.xsd"><acquisto id="1" id_cliente="3" data="2024-06-08" crediti_bonus_utilizzati="0" totale_effettivo="170" crediti_bonus_ricevuti="3"><prodotti><prodotto id_prodotto="1" prezzo="170"/></prodotti><indirizzo_consegna>Via Rossi 15 Latina 04100</indirizzo_consegna></acquisto><acquisto id="2" id_cliente="3" data="2024-06-10" crediti_bonus_utilizzati="0" totale_effettivo="67" crediti_bonus_ricevuti="3"><prodotti><prodotto id_prodotto="2" prezzo="67"/></prodotti><indirizzo_consegna>Via Verdi 1 Roma 00042</indirizzo_consegna></acquisto><acquisto id="3" id_cliente="4" data="2024-06-15" crediti_bonus_utilizzati="0" totale_effettivo="237" crediti_bonus_ricevuti="6"><prodotti><prodotto id_prodotto="1" prezzo="170"/><prodotto id_prodotto="2" prezzo="67"/></prodotti><indirizzo_consegna>Via Neri 78 Aosta 11100</indirizzo_consegna></acquisto><acquisto id="4" id_cliente="4" data="2024-07-25" crediti_bonus_ricevuti="14" crediti_bonus_utilizzati="15" totale_effettivo="296"><prodotti><prodotto id_prodotto="2" prezzo="205"/><prodotto id_prodotto="4" prezzo="91"/></prodotti><indirizzo_consegna>Via Rossi 10</indirizzo_consegna></acquisto><acquisto id="5" id_cliente="3" data="2024-07-25" crediti_bonus_ricevuti="7" crediti_bonus_utilizzati="0" totale_effettivo="340"><prodotti><prodotto id_prodotto="1" prezzo="340"/></prodotti><indirizzo_consegna>Via Dei Girasoli 10</indirizzo_consegna></acquisto><acquisto id="6" id_cliente="4" data="2024-07-25" crediti_bonus_ricevuti="7" crediti_bonus_utilizzati="0" totale_effettivo="340"><prodotti><prodotto id_prodotto="1" prezzo="340"/></prodotti><indirizzo_consegna>Via Caldara 8</indirizzo_consegna></acquisto><acquisto id="7" id_cliente="4" data="2024-07-25" crediti_bonus_ricevuti="7" crediti_bonus_utilizzati="0" totale_effettivo="340"><prodotti><prodotto id_prodotto="1" prezzo="340"/></prodotti><indirizzo_consegna>Via Rossi 10</indirizzo_consegna></acquisto><acquisto id="8" id_cliente="4" data="2024-07-25" crediti_bonus_ricevuti="0" crediti_bonus_utilizzati="10" totale_effettivo="66"><prodotti><prodotto id_prodotto="3" prezzo="66"/></prodotti><indirizzo_consegna>Via Rossi 10</indirizzo_consegna></acquisto><acquisto id="9" id_cliente="8" data="2024-07-26" crediti_bonus_ricevuti="14" crediti_bonus_utilizzati="0" totale_effettivo="277"><prodotti><prodotto id_prodotto="2" prezzo="205"/><prodotto id_prodotto="5" prezzo="72"/></prodotti><indirizzo_consegna>Via dei Tulipani 3</indirizzo_consegna></acquisto><acquisto id="10" id_cliente="8" data="2024-07-26" crediti_bonus_ricevuti="1" crediti_bonus_utilizzati="11" totale_effettivo="74"><prodotti><prodotto id_prodotto="3" prezzo="74"/></prodotti><indirizzo_consegna>Via dei Tulipani 2</indirizzo_consegna></acquisto></acquisti>
