=== matteoventali/repository_homework/tesina/xml/schema/schemaCatalogoProdotti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="catalogo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prodotto" minOccurs="1" maxOccurs="unbounded" />  
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prodotto">
        <xsd:complexType>
            <xsd:sequence>
               <xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
               <xsd:element ref="prezzo_listino" minOccurs="1" maxOccurs="1"/>
               <xsd:element ref="percorso_immagine" minOccurs="1" maxOccurs="1"/>
               <xsd:element ref="specifiche" minOccurs="1" maxOccurs="1"/>
               <xsd:element ref="descrizione" minOccurs="1" maxOccurs="1"/>
               <xsd:element ref="offerta_speciale" minOccurs="0" maxOccurs="1" />
            </xsd:sequence>

            <xsd:attribute name="id_tipo" type="xsd:integer" use="required"/>
            <xsd:attribute name="id_categoria" type="xsd:integer" use="required"/>
            <xsd:attribute name="id" type="xsd:integer" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="offerta_speciale">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="data_inizio" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data_fine" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>

            <xsd:attribute name="percentuale" type="xsd:integer" use="required" />
            <xsd:attribute name="crediti" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string"/>
    <xsd:element name="descrizione" type="xsd:string"/>
    <xsd:element name="specifiche" type="xsd:string"/>
    <xsd:element name="percorso_immagine" type="xsd:string"/>
    <xsd:element name="prezzo_listino" type="xsd:float"/>
    <xsd:element name="data_inizio" type="xsd:date" />
    <xsd:element name="data_fine" type="xsd:date" />
</xsd:schema>

=== matteoventali/repository_homework/tesina/xml/catalogoProdotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./schemaCatalogoProdotti.xsd">

    <prodotto id="1" id_categoria="1" id_tipo="1">
        <nome>APPLE MacBook Air</nome>
        <prezzo_listino>170</prezzo_listino>
        <percorso_immagine>../img/immagine_mac</percorso_immagine>
        <specifiche>
            Risoluzione: 2560 x 1600 Pixel
            Touchscreen: No
            Diagonale schermo (pollici): 13.3 pollici
            Tipo di schermo: LED
            Dimensione memoria RAM: 8 GB
            Memoria massima supportata: 8 GB
            Processore: M1 CPU 8-core
        </specifiche>
        <descrizione>
            Macbook Air supera ogni sfida con leggerezza.
            E con il chip M3, il notebook piu' amato al mondo diventa ancora piu' potente.
        </descrizione>
    </prodotto>

    <prodotto id="2" id_categoria="3" id_tipo="1">
        <nome>Samsung TV UE50CU7090UXZT</nome>
        <prezzo_listino>74</prezzo_listino>
        <percorso_immagine>../img/immagine_tvSamsung</percorso_immagine>
        <specifiche>
            Dimensioni schermo: 50 Pollici
            Marchio: Samsung
            Tecnologia dello schermo: LED
            Risoluzione: 4K
            Frequenza di aggiornamento: 60 Hz
            Caratteristica speciale: Built-In Speaker
            Componenti inclusi: 1x Smart TV, 1x Remote
            Tecnologia di connettivita': Bluetooth, Wi-Fi, USB, Ethernet, HDMI
            Dimensioni del prodotto: 111P x 22,1l x 70,3H cm
            Servizi Internet supportati: Netflix, Disney Plus, Prime Video, YouTube
        </specifiche> 
        <descrizione>
            Processore Crystal 4K con risoluzione 4K per sfumature di colore vivide e realistiche. 
            Tecnologia PurColor per una resa cromatica precisa con una vasta gamma di colori. 
            Design elegante e raffinato senza cornice su 3 lati.
        </descrizione>
        <offerta_speciale percentuale="10" crediti="2">
            <data_inizio>2024-06-01</data_inizio>
            <data_fine>2024-06-30</data_fine>
        </offerta_speciale>
    </prodotto>
</catalogo>

=== matteoventali/repository_homework/tesina/xml/documenti/catalogoProdotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaCatalogoProdotti.xsd"><prodotto id="1" id_categoria="1" id_tipo="1"><nome>Apple Macbook Air</nome><prezzo_listino>400</prezzo_listino><percorso_immagine>../img/immagini_prodotti/macbook.jpg</percorso_immagine><specifiche>Dimensioni diagonale schermo: 14.2  &#13;
Modello del processore: M3 Pro  &#13;
RAM installata: 18 GB &#13;
Capacit√† SSD: 512 GB &#13;
Sistema operativo incluso: macOS Sonoma  &#13;
Scheda grafica dedicata: Non disponibile &#13; Risoluzione del display: 3024 x 1964 pixel &#13;
Touch screen: No</specifiche><descrizione>Portatile molto costoso della Apple</descrizione><offerta_speciale percentuale="10" crediti="2">
    <data_inizio>2024-06-01</data_inizio>
    <data_fine>2024-12-30</data_fine>
</offerta_speciale></prodotto></catalogo>

=== matteoventali/repository_homework/tesina/docs/xml_pop/catalogoProdotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/schemaCatalogoProdotti.xsd"><prodotto id="1" id_categoria="2" id_tipo="1" mostra="true"><nome>Iphone 15 Pro Max</nome><prezzo_listino>260</prezzo_listino><percorso_immagine>../img/immagini_prodotti/iphone15.jpg</percorso_immagine><specifiche>Marchio Apple&#13;Sistema operativo iOS&#13;Capacità della memoria 256 GB&#13;Dimensioni schermo 6,7 Pollici&#13;Frequenza di aggiornamento 120 Hz&#13;Nome modello iPhone 15 Pro Max&#13;Carrier wireless Tutti i vettori&#13;Tecnologia cellulare 5G&#13;Tecnologia di connettività Wi-Fi, USB&#13;Colore Titanio nero</specifiche><descrizione>Smartphone molto costoso</descrizione></prodotto><prodotto id="2" id_categoria="1" id_tipo="1" mostra="true"><nome>Apple MacBook Air</nome><prezzo_listino>170</prezzo_listino><percorso_immagine>../img/immagini_prodotti/macbook.jpg</percorso_immagine><specifiche>Risoluzione: 2560 x 1600 Pixel&#13;Touchscreen: No&#13;Diagonale schermo (pollici): 13.3 pollici&#13;Tipo di schermo: LED&#13;Dimensione memoria RAM: 8 GB&#13;Memoria massima supportata: 8 GB&#13;Processore: M1 CPU 8-core</specifiche><descrizione>Macbook Air supera ogni sfida con leggerezza. E con il chip M3, il notebook piu' amato al mondo diventa ancora piu' potente.</descrizione><offerta_speciale percentuale="10" crediti="5"><data_inizio>2024-07-26</data_inizio><data_fine>2024-12-31</data_fine></offerta_speciale></prodotto><prodotto id="3" id_categoria="3" id_tipo="1" mostra="true"><nome>Samsung TV UE50CU7090UXZT</nome><prezzo_listino>74</prezzo_listino><percorso_immagine>../img/immagini_prodotti/samsung.jpg</percorso_immagine><specifiche>Dimensioni schermo: 50 Pollici&#13;Marchio: Samsung&#13;Tecnologia dello schermo: LED&#13;Risoluzione: 4K&#13;Frequenza di aggiornamento: 60 Hz&#13;Caratteristica speciale: Built-In Speaker&#13;Componenti inclusi: 1x Smart TV, 1x Remote&#13;Tecnologia di connettivita': Bluetooth, Wi-Fi, USB, Ethernet, HDMI&#13;Dimensioni del prodotto: 111P x 22,1l x 70,3H cm&#13;Servizi Internet supportati: Netflix, Disney Plus, Prime Video, YouTube</specifiche><descrizione>Processore Crystal 4K con risoluzione 4K per sfumature di colore vivide e realistiche. Tecnologia PurColor per una resa cromatica precisa con una vasta gamma di colori. Design elegante e raffinato senza cornice su 3 lati.</descrizione></prodotto><prodotto id="4" id_categoria="5" id_tipo="3" mostra="true"><nome>PlayStation 5</nome><prezzo_listino>100</prezzo_listino><percorso_immagine>../img/immagini_prodotti/playstation5.jpg</percorso_immagine><specifiche>CPU: x86-64-AMD Ryzen™ “Zen 2”&#13;GPU: AMD Radeon™ RDNA 2-based graphics engine&#13;Memoria: 16 GB RAM GDDR6&#13;Larghezza di banda: 448 GB/s&#13;Supporto al disco rigido: si</specifiche><descrizione>Fino a 120 FPS con uscita a 120 Hz.&#13;Goditi un gameplay fluido con frame rate elevato fino a 120 FPS per giochi compatibili, con supporto per l'uscita a 120 Hz su display 4KTecnologia HDR.&#13;Su una TV HDR, i giochi PS5 compatibili mostrano una gamma di colori vivaci e realistici.</descrizione></prodotto><prodotto id="5" id_categoria="4" id_tipo="1" mostra="true"><nome>Whirlpool FFB 948 BSV</nome><prezzo_listino>83</prezzo_listino><percorso_immagine>../img/immagini_prodotti/lavatrice.jpg</percorso_immagine><specifiche>Produttore: Whirlpool&#13;Riferimento produttore: FFB948BSVIT&#13;Dimensioni prodotto: ‎63 x 64 x 87 cm&#13;ASIN: B0D63HRFQM</specifiche><descrizione>Caratteristiche di questa lavatrice a libera installazione Whirlpool: colore bianco. Cestello spazioso e ampio da 9,0 kg. Classe energetica A.&#13;Centrifuga a 1400 giri al minuto, rapida ed efficiente. Esclusiva tecnologia 6° SENSO che adatta dinamicamente le impostazioni in base alle caratteristiche di ciascun carico, garantendo una cura ideale per tutti i tessuti.</descrizione></prodotto><prodotto id="6" id_categoria="5" id_tipo="1" mostra="true"><nome>Cuffie Btootos</nome><prezzo_listino>6</prezzo_listino><percorso_immagine>../img/immagini_prodotti/cuffie.jpg</percorso_immagine><specifiche>Marchio: Btootos&#13;
Colore: Nero&#13;
Posizionamento sull’orecchio: In-ear&#13;
Fattore di forma: In-ear&#13;
Controllo del rumore: Isolamento acustico&#13;
Nome modello: A90 Pro&#13;
Tecnologia di connettività: Senza fili&#13;
Tecnologia di comunicazione wireless: Bluetooth&#13;
Componenti inclusi: Stazione di ricarica, Punte auricolari</specifiche><descrizione>Cuffie nere bellissime</descrizione></prodotto></catalogo>
